### ISSUE TITLE
Incorrect composer.json

### ISSUE THREAD

**Issue by ReArmedHalo** [SocialiteProviders/Generators#22]
I may be wrong on this, this is really my first dive into composer packages, but the PSR-4 line generated by the console command to insert into Laravel's composer.json is wrong.

https://github.com/SocialiteProviders/Generators/blob/2ae61ca0c8674b1c9117dbbe777d72608ba7bde5/src/Console/MakeProviderCommand.php#L119

The folder structure on disk is `/SocialiteProviders/src/{{provider_name}}` but the composer file gets written out to ` SocialiteProviders\\{{$provider_name}}\\`

`$contents['autoload']['psr-4']["SocialiteProviders\\$providerName\\"] = "SocialiteProviders/$providerName/";`

Should be

`$contents['autoload']['psr-4']["SocialiteProviders\\$providerName\\"] = "SocialiteProviders/src/$providerName/";`

I had to change my composer.json to get `composer dumpautoload` to work after adding my provider to the `EventServiceProvider.php` listener for the `SocialiteWasCalled` event. This might just be a n00b thing for me but figured it didn't hurt to check.

**Comment by m1guelpf** [comment]
Could you make a PR to fix this @ReArmedHalo?

**Comment by ReArmedHalo** [comment]
@m1guelpf hope I did that right... :P - Not used to working in others repositories :)

https://github.com/SocialiteProviders/Generators/pull/23
