### ISSUE TITLE
How to use generated provider in app for testing?

### ISSUE THREAD

**Issue by techenby** [SocialiteProviders/Generators#6]
I feel like the readme is missing the crucial step for using the provider in an app. How is this accomplished?

**Comment by faustbrian** [comment]
You can just add the Providers `src` directory to `psr-4` in `autoload` in `composer.json` and then run `composer dumpautoload` and from there on proceed as usual.

**Comment by sjelfull** [comment]
Still, it would be helpful if this was part of the readme.

**Comment by faustbrian** [comment]
I would say this is assumed to be common knowledge if you start to develop packages for composer, especially when you read the composer docs which should be done before starting to develop packages.

**Comment by sjelfull** [comment]
I think the point to make is that the readme only take you so far, and does not let you get up and running as quickly. 

Even if you have read the composer docs, someone might assume that it should just work, which I actually did when I started. When it doesn't, you have to figure out why.

I would also say that the philosophy of the main Laravel docs is to be as complete and friendly as possible, with as few assumptions as possible. "Common knowledge" for one person isn't the same for another.

Is there anything problematic about adding the note?

**Comment by faustbrian** [comment]
You are free to send a PR.
