### ISSUE TITLE
Can't use laravel 5.4.* 

### ISSUE THREAD

**Issue by Crowdedlight** [SocialiteProviders/Generators#7]
Problem 1
    - Conclusion: remove laravel/framework v5.4.6
    - Conclusion: don't install laravel/framework v5.4.6
    - socialiteproviders/generators v3.0.0 requires illuminate/console 5.1.* || 5.2.* || 5.3.* -> 

Snippet of error message when installing though composer on a 5.4.6 version

**Comment by faustbrian** [comment]
Fixed with new release.
