### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by iversonlin330** [SocialiteProviders/Generators#9]
When I run php artisan make:socialite Test --spec=oauth2 --author=YourName --email=your@name.com

I dont find any providers have generate in SocialiteProviders/Manager.

I dont no where can set my AuthUrl and TokenUrl before generate.

**Comment by faustbrian** [comment]
Check this line to understand where the generated provider will go.

https://github.com/SocialiteProviders/Generators/blob/master/src/Compilers/Compiler.php#L75
